# Generated by Django 5.2.14 on 2026-06-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('period', models.CharField(help_text='Например: Каждую пятницу', max_length=100)),
                ('body', models.TextField()),
                ('image', models.URLField()),
                ('badge', models.CharField(default='Акция', max_length=50)),
                ('badge_style', models.CharField(choices=[('terracotta', 'Оранжевый'), ('dark', 'Тёмный'), ('green', 'Зелёный')], default='terracotta', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('footer_note', models.CharField(blank=True, max_length=200)),
                ('link_url', models.CharField(blank=True, max_length=200)),
                ('link_text', models.CharField(blank=True, max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-sort_order', '-created_at'],
            },
        ),
    ]
